### ISSUE TITLE
Help required importing a custom WordPress theme from GitHub into Playground 

### ISSUE THREAD

**Issue by AmnestyAM** [WordPress/blueprints#58]
Hello.
I have been experimenting with playground, thanks for building this :-) 

I have this blueprint https://github.com/amnestywebsite/humanity-blueprint/blob/main/blueprint.json 
https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/amnestywebsite/humanity-blueprint/main/blueprint.json 

Which is trying to install this theme https://github.com/amnestywebsite/humanity-theme/releases

Which has been uploaded here https://github.com/amnestywebsite/humanity-blueprint/blob/main/humanity-theme.zip 

The backend editor experience seems to work as I can 

1. create a post
2. add a tile
3. add a custom block 
4. add data to the custom block 

When I try to view the post I see a spinning icon and looking at the console while running the blue print gives me the below. 

```
The theme seems to show in the editor 
Error: PHP.run() failed with exit code 255 and the following output: 
logToConsole @ /worker-thread-d40a8…te-slug=wordpress:1
index.js:222  PHP.run() failed with exit code 255 and the following output:  Error: PHP.run() failed with exit code 255 and the following output: 
    at PHP.run (https://playground.wordpress.net/worker-thread-d40a8ab7.js?wpVersion=6.4&phpVersion=8.2&php-extension=iconv&php-extension=mbstring&php-extension=xml-bundle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:53:1748)
    at async PlaygroundWorkerEndpoint.run (https://playground.wordpress.net/worker-thread-d40a8ab7.js?wpVersion=6.4&phpVersion=8.2&php-extension=iconv&php-extension=mbstring&php-extension=xml-bundle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:4:8867)
$o @ index.js:222
index.js:219  Error: PHP.run() failed with exit code 255 and the following output: 
    at PHP.run (/worker-thread-d40a8ab7.js?wpVersion=6.4&phpVersion=8.2&php-extension=iconv&php-extension=mbstring&php-extension=xml-bundle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:53:1748)
    at async PlaygroundWorkerEndpoint.run (/worker-thread-d40a8ab7.js?wpVersion=6.4&phpVersion=8.2&php-extension=iconv&php-extension=mbstring&php-extension=xml-bundle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:4:8867)
$o @ index.js:219
builder.html-f350f1dc.js:5  Error: Error when executing the blueprint step #6 ({"step":"importWxr","file":{"resource":"url","url":"https://raw.githubusercontent.com/amnestywebsite/humanity-blueprint/main/humanitythemeContent.xml"}}) : PHP.run() failed with exit code 255 and the following output: 
    at Object.run (index.js:8782:32)
    at async Sd (index.js:8892:3)
    at async Ud (index.js:9255:43)
    at async k (builder.html-f350f1dc.js:6:561)Caused by: Error: PHP.run() failed with exit code 255 and the following output: 
    at PHP.run (/worker-thread-d40a8ab7.js?wpVersion=6.4&phpVersion=8.2&php-extension=iconv&php-extension=mbstring&php-extension=xml-bundle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:53:1748)
    at async PlaygroundWorkerEndpoint.run (/worker-thread-d40a8ab7.js?wpVersion=6.4&phpVersion=8.2&php-extension=iconv&php-extension=mbstring&php-extension=xml-bundle&php-extension=gd&networking=yes&storage=&site-slug=wordpress:4:8867)
```

It would be amazing if I could even get a single post or page to load.

Once I get this working I was planning to submit it to your gallery. 

I am able to send a full back up on another channel if that helps? 

Thanks,

**Comment by AmnestyAM** [comment]
Hi @bph thanks for your help so far, here is the issue

**Comment by bph** [comment]
Hi there, Austin, 

That's a known issue: could you try to use the github-proxy.com? It's not a permanent solution. The team is working on a permanent solution, that's why there isn't much of documentation... 

Try something like this: https://github-proxy.com/proxy/?repo=https://github.com/amnestywebsite/humanity-theme/

**Comment by AmnestyAM** [comment]
Hi @bph I tried that method and couldn't get it to work, thanks for the suggestion though. If it helps I am happy to close this issue and watch for an update on the issue in the playground repo https://github.com/WordPress/playground-tools/issues/314 

Thanks again

**Comment by adamziel** [comment]
@AmnestyAM I replied in https://github.com/WordPress/playground-tools/issues/314. Let's close this one.
